### ISSUE TITLE
Swift Package Manager Error - The data couldn't be read because it isn't in the correct format.

### ISSUE THREAD

**Issue by djk12587** [GoSkip/SkipTools-Legacy#2]
Hello, I am getting a compile error on Xcode 12.5, when attempting to use the SkipTools-Legacy (4.0.1) with Swift Package Manager. This is from a brand new project with no other dependencies.
<img width="1123" alt="Screen Shot 2021-07-14 at 11 23 47 AM" src="https://user-images.githubusercontent.com/1069268/125659175-08b7060f-4888-47f0-ab5c-4058f5f636b8.png">

Xcode does not provide any further information about the error.
<img width="1120" alt="Screen Shot 2021-07-14 at 11 28 34 AM" src="https://user-images.githubusercontent.com/1069268/125659234-0ac493d4-1ad8-4d69-be2a-8cd90ebac31f.png">

**Comment by jonesrajee** [comment]
@djk12587 It appears there is an issue with SPM fetching files from `git lfs`

Please give me a second to triage this issue and find a solution. 

In the meantime, you can download the `.zip` of the xcframework directly from the release tab
> https://github.com/GoSkip/SkipTools-Legacy/releases/tag/4.0.1

**Comment by jonesrajee** [comment]
@djk12587 Please re-try as Version 4.0.1 has been re-released with this fixed

**Comment by djk12587** [comment]
that fixed it, thanks!
